name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 complete"
      - name: Step two
        run: echo "Log from step two"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
          # What does the cow say?
          text: 'Ready for prod–ship it!'
          # Color of your cow
          color: 'magenta' 
